#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m config debug_output on

# ====== Variables =============================

gaps_top="0"
gaps_bottom="0"
gaps_left="0"
gaps_right="0"
gaps_inner="1"

#normal_border_color="010101"
#focused_border_color="808080"
#preselect_border_color="2d74da"

# ====== Tiling settings =======================

yabai -m config layout                      bsp


yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         on
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                x-axis
yabai -m config window_insertion_point      focused
# yabai -m config window_animation_duration   0

# ====== Space Settings ========================

yabai -m config --space 3 layout stack
yabai -m config --space 8 layout float
# yabai -m config --space 6 layout stack

yabai -m space 1 --label General
yabai -m space 2 --label Files
yabai -m space 3 --label IDE
yabai -m space 4 --label Browser
yabai -m space 5 --label Dev
yabai -m space 6 --label Messages
yabai -m space 7 --label Productivity
yabai -m space 8 --label Random

# ====== List of rules =========================

# ======== Management Rules ====================

yabai -m rule --add label="1Password" app="^1Password$" manage=off sub-layer=below
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Bartender" app="^Bartender$" manage=off
yabai -m rule --add label="BetterTouchTool" app="^BetterTouchTool$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off sub-layer=below
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="FaceTime" app="^FaceTime$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Installer" app="^Installer$" manage=off
yabai -m rule --add label="KeeWeb" app="^KeeWeb$" manage=off
yabai -m rule --add label="Keka" app="^Keka$" manage=off
yabai -m rule --add label="Keychain Access" app="^Keychain Access$" manage=off
yabai -m rule --add label="WindowSwitcher" app="^WindowSwitcher$" manage=off
yabai -m rule --add label="Preview" app="^Preview$" manage=off sub-layer=below
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Excel" app="^Microsoft Excel$" title="^Find & Replace$" manage=off
yabai -m rule --add label="SetApp Launcher" app="^SetappLauncher$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="TeamViewer" app="^TeamViewer$" manage=off sub-layer=below
yabai -m rule --add label="TimeMachine" app="^Time Machine$" manage=off
yabai -m rule --add label="TablePlus Connections" app="^TablePlus$" title="^(Connection...)$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off sub-layer=below
yabai -m rule --add label="BusyCal" app="^BusyCal$" manage=off

# ======== App to Space Management ==============

# Files
yabai -m rule --add app="^Finder$" space="^Files"
yabai -m rule --add app="^Transmit$" space="^Files"

# IDE
# yabai -m rule --add app="^Code$" space="^IDE"
yabai -m rule --add app="^TablePlus$" space="^IDE"

# Browser
# yabai -m rule --add app="^Google Chrome$" space="^Browser"
# yabai -m rule --add app="^Safari$" space="^Browser"

# Dev
yabai -m rule --add app="^kitty$" space="^Dev"

# Messages
yabai -m rule --add app="^Microsoft Outlook" space="^Messages"

# Random
yabai -m rule --add app="^Spotify$" space="^Random"
yabai -m rule --add app="^pascom Client$" space="^Random"

yabai -m rule --apply
# ====== Signals ===============================

#yabai -m signal --add event=space_changed label="Update Hammerspoon Space on Space change" action="hs -A -c 'spacebar:update()'"
#yabai -m signal --add event=window_created label="Update Hammerspoon Space on window creation" action="hs -A -c 'spacebar:update()'"
#yabai -m signal --add event=window_destroyed label="Update Hammerspoon Space on window deletion" action="hs -A -c 'spacebar:update()'"
#yabai -m signal --add event=window_moved label="Update Hammerspoon Space on window moved" action="hs -A -c 'spacebar:update()'"
#yabai -m signal --add event=display_added label="Update Hammerspoon Space on display added" action="hs -A -c 'spacebar:update()'"
#yabai -m signal --add event=display_removed label="Update Hammerspoon Space on display removed" action="hs -A -c 'spacebar:update()'"

yabai -m signal --add event=space_changed label="Update Hammerspoon Space on Space change" action="osascript -e 'tell application \"BetterTouchTool\"' -e 'refresh_widget \"DD66DB15-2536-4353-AEC7-A9F5D668A1B7\"' -e 'end tell'"
yabai -m signal --add event=window_created label="Update Hammerspoon Space on window creation" action="osascript -e 'tell application \"BetterTouchTool\"' -e 'refresh_widget \"DD66DB15-2536-4353-AEC7-A9F5D668A1B7\"' -e 'end tell'"
yabai -m signal --add event=window_destroyed label="Update Hammerspoon Space on window deletion" action="osascript -e 'tell application \"BetterTouchTool\"' -e 'refresh_widget \"DD66DB15-2536-4353-AEC7-A9F5D668A1B7\"' -e 'end tell'"
yabai -m signal --add event=window_moved label="Update Hammerspoon Space on window moved" action"osascript -e 'tell application \"BetterTouchTool\"' -e 'refresh_widget \"DD66DB15-2536-4353-AEC7-A9F5D668A1B7\"' -e 'end tell'"
yabai -m signal --add event=display_added label="Update Hammerspoon Space on display added" action="osascript -e 'tell application \"BetterTouchTool\"' -e 'refresh_widget \"DD66DB15-2536-4353-AEC7-A9F5D668A1B7\"' -e 'end tell'"
yabai -m signal --add event=display_removed label="Update Hammerspoon Space on display removed" action="osascript -e 'tell application \"BetterTouchTool\"' -e 'refresh_widget \"DD66DB15-2536-4353-AEC7-A9F5D668A1B7\"' -e 'end tell'"

yabai -m signal --add event=window_destroyed label="Focus window below cursor after closing window" action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated label="Focus window below cursor after closing application" action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# ====== Updater ===============================

# YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &
